variables:
  IMAGE_NAME: olgaalekhina/step
  IMAGE_TAG: app-1.0

stages:
  - build

build_image:
  stage: build
  image: docker:27.3.1
  services:
    - docker:27.3.1-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
